#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

# El repo, para leer setup.sh y dominios.txt sin depender de desde dónde se corra.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Ningún secreto se guarda en disco. Apuntamos ENV_FILE a un archivo que no
# existe para que `ask`/`ask_secret` no ofrezcan como default lo que haya en el
# .env real del repo — ahí vive un RAILWAY_TOKEN inválido que arruinaría todo.
ENV_FILE="$(mktemp -u)"

RAILWAY="env -u RAILWAY_TOKEN railway"

# copy_clip "texto" — al portapapeles, que es como esto se pega en claude.ai.
copy_clip() {
  if   command -v pbcopy  >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v xclip   >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  else warn "sin portapapeles: copialo a mano de lo de arriba"; return 1; fi
  printf '  %s✓ copiado%s al portapapeles\n' "$GREEN" "$RESET"
}

# rw_var NOMBRE SERVICIO — el valor de una variable de Railway, o vacío.
rw_var() {
  $RAILWAY variables --service "$2" --kv 2>/dev/null | grep "^$1=" | cut -d= -f2- || true
}

banner "Este repo desde la nube — configurar el entorno de Claude Code on the web"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "La cuenta de GitHub"
say "El repo es privado de danielmedinac22. Si conectás la de Simetrik, la sesión"
say "falla al clonar con «Session creation failed» y parece falta de capacidad."
ACTIVA="$(gh api user --jq .login 2>/dev/null || echo '?')"
if [[ "$ACTIVA" == "danielmedinac22" ]]; then
  printf '  %s✓%s la cuenta activa ya es danielmedinac22\n' "$GREEN" "$RESET"
else
  warn "la cuenta activa es '$ACTIVA'"
  if confirm "¿Cambio a danielmedinac22?"; then
    gh auth switch --user danielmedinac22 && printf '  %s✓%s cambiada\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("cambiar la cuenta de gh a danielmedinac22")
  fi
fi
pause "Enter para seguir"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Conectar GitHub con Claude Code"
say "Claude necesita poder clonar el repo desde su VM."
open_url "https://claude.ai/code"
step "Si es tu primera vez, seguí el onboarding y autorizá la GitHub App de Claude."
step "Si ya lo hiciste, verificá que la cuenta conectada sea danielmedinac22."
note "Alternativa desde la terminal: correr /web-setup dentro de Claude Code,"
note "que sincroniza el token de tu gh local con tu cuenta de claude.ai."
pause "Enter cuando GitHub esté conectado"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Crear el entorno y pegar el setup script"
say "El setup script instala los CLI de Railway y Vercel y fija la versión de pnpm."
say "Corre una sola vez por entorno; después Anthropic fotografía el disco."
copy_clip "$(cat "$REPO/docs/nube/setup.sh")" || true
open_url "https://claude.ai/code"
step "Abrí el selector de entorno (el ícono de nube) y creá uno nuevo."
step "Ponele un nombre reconocible, por ejemplo 'whatsapp-agent'."
step "En el campo 'Setup script', pegá lo que quedó en el portapapeles."
pause "Enter cuando el setup script esté pegado"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Los dominios permitidos"
say "Por defecto la sesión solo alcanza registries y GitHub. Sin esta lista no"
say "llega a la base de producción ni a OpenRouter, aunque las claves estén bien."
copy_clip "$(cat "$REPO/docs/nube/dominios.txt")" || true
step "En el mismo diálogo, poné 'Network access' en Custom."
step "Dejá MARCADO 'Also include default list of common package managers'."
step "Pegá la lista en 'Allowed domains'."
note "GitHub no hace falta listarlo: va por un proxy aparte."
pause "Enter cuando los dominios estén puestos"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Reunir las variables"
say "Las que ya existen las leo de Railway. Las dos de deploy las creás vos ahora."
printf '\n'
DB_URL="$(rw_var DATABASE_PUBLIC_URL Postgres)"
OR_KEY="$(rw_var OPENROUTER_API_KEY whatsapp-worker)"
WK_TOK="$(rw_var WORKER_API_TOKEN whatsapp-worker)"
PUB_URL="$(rw_var PUBLIC_URL whatsapp-worker)"
KP_KEY="$(rw_var KAPSO_API_KEY whatsapp-worker)"
for par in "DATABASE_PUBLIC_URL:$DB_URL" "OPENROUTER_API_KEY:$OR_KEY" \
           "WORKER_API_TOKEN:$WK_TOK" "PUBLIC_URL:$PUB_URL" "KAPSO_API_KEY:$KP_KEY"; do
  n="${par%%:*}"; v="${par#*:}"
  if [[ -n "$v" ]]; then printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$n"
  else warn "no pude leer $n de Railway"; SKIPPED+=("$n: conseguilo a mano"); fi
done
printf '\n'
say "Ahora el token de Railway. Es un token DE PROYECTO, no personal."
open_url "https://railway.com/project/623afd57-8396-411a-a60a-5c7c2a615692/settings/tokens"
step "Creá un token para el entorno 'production' y copialo."
ask_secret RW_TOKEN "Pegá el token de Railway:"
printf '\n'
say "Y el de Vercel, para deployar el dashboard."
open_url "https://vercel.com/account/tokens"
step "Create Token, alcance el proyecto whatsapp-agent, copialo."
ask_secret VC_TOKEN "Pegá el token de Vercel:"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Pegar las variables en el entorno"
BLOQUE="DATABASE_PUBLIC_URL=$DB_URL
OPENROUTER_API_KEY=$OR_KEY
WORKER_API_TOKEN=$WK_TOK
PUBLIC_URL=$PUB_URL
KAPSO_API_KEY=$KP_KEY
RAILWAY_TOKEN=$RW_TOKEN
VERCEL_TOKEN=$VC_TOKEN"
copy_clip "$BLOQUE" || printf '%s\n' "$BLOQUE"
warn "Estos valores quedan guardados en la config del entorno, que NO es un"
warn "almacén de secretos: cualquiera que use ese entorno los puede leer."
note "Como es un entorno personal, el alcance es el de tu cuenta de claude.ai."
note "Si algún día lo compartís con la organización, sacá de ahí las credenciales."
printf '\n'
step "En el diálogo del entorno, pegá el bloque en 'Environment variables'."
step "Guardá el entorno."
pause "Enter cuando esté guardado"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "El .mcp.json y la prueba"
if [[ -f "$REPO/.mcp.json" ]]; then
  printf '  %s✓%s .mcp.json ya existe\n' "$GREEN" "$RESET"
else
  say "Falta declarar Linear a nivel de proyecto para que viaje al clon."
  if confirm "¿Lo creo?"; then
    printf '%s\n' '{
  "mcpServers": {
    "linear-pcd": {
      "type": "http",
      "url": "https://mcp.linear.app/mcp"
    }
  }
}' > "$REPO/.mcp.json"
    printf '  %s✓%s escrito — acordate de commitearlo\n' "$GREEN" "$RESET"
    SKIPPED+=("commitear .mcp.json")
  else
    SKIPPED+=("crear .mcp.json")
  fi
fi
printf '\n'
warn "La URL de Linear es la misma para todos los workspaces: quien decide cuál"
warn "es el token. Confirmá con get_workspace antes del primer write, o el"
warn "ticket aparece en el tablero de otro cliente sin fallar con error."
printf '\n'
say "Probalo: abrí una sesión en la nube sobre whatsapp-agent y pedile esto:"
note "  «corré pnpm -r typecheck y después scripts/prueba-openrouter.ts»"
say "Si las dos cosas pasan, el entorno quedó bien."

finish
